### ISSUE TITLE
Different types and (default) map markers

### ISSUE THREAD

**Issue by DangerousDetlef** [joscha999/PiratenKarte#6]
We have at least two types of "Plakate" normal ones and "Großplakate". It would be great if one could choose between them and if they'd get distinct map makers. It does not need to be something fancy, maybe one orange circle 🟠 and one purple 🟣 would suffice.

**Comment by joscha999** [comment]
Since markers are completely made via CSS/HTML they can be anything - internally the Storage object marker for example is a rounded square.

For Großplakate it'd make sense to use something similar where the marker is a little wider so it's immediately noticable.
Adding color *should* be really easy via a *simple* color picker - I'll add that first with some option to save colors or just pre-select from an existing range.

I'll probably consider allowing for users to create their own styles later - it requires a little more work but is definitely possible :)

**Comment by DangerousDetlef** [comment]
Cool, maybe you can then simply add some SVGs? You can probably find some suitable ones for "Plakat" or "Großplakat" here https://www.iconfinder.com/search?q=poster&price=free or other sites similar :)
